// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelCompany.DBLayer.PostgreSQL;

namespace TravelCompany.DBLayer.PostgreSQL.Migrations
{
    [DbContext(typeof(PostgreSQLDbContext))]
    [Migration("20201203140846_SetUUIDasKey")]
    partial class SetUUIDasKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TravelCompany.Model.Agent", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("TravelAgencyUUID")
                        .HasColumnType("uuid");

                    b.HasKey("UUID");

                    b.HasIndex("TravelAgencyUUID");

                    b.ToTable("Agent");
                });

            modelBuilder.Entity("TravelCompany.Model.TravelAgency", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("UUID");

                    b.ToTable("TravelAgency");
                });

            modelBuilder.Entity("TravelCompany.Model.Agent", b =>
                {
                    b.HasOne("TravelCompany.Model.TravelAgency", "TravelAgency")
                        .WithMany("Agents")
                        .HasForeignKey("TravelAgencyUUID");

                    b.Navigation("TravelAgency");
                });

            modelBuilder.Entity("TravelCompany.Model.TravelAgency", b =>
                {
                    b.Navigation("Agents");
                });
#pragma warning restore 612, 618
        }
    }
}
