// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelCompany.DBLayer.PostgreSQL;

namespace TravelCompany.DBLayer.PostgreSQL.Migrations
{
    [DbContext(typeof(PostgreSQLDbContext))]
    [Migration("20201204134537_RemovedNumericIdentity")]
    partial class RemovedNumericIdentity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TravelCompany.DataAccess.Agency", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("UUID");

                    b.ToTable("Agency");
                });

            modelBuilder.Entity("TravelCompany.DataAccess.Agent", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgencyUUID")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UUID");

                    b.HasIndex("AgencyUUID");

                    b.ToTable("Agent");
                });

            modelBuilder.Entity("TravelCompany.DataAccess.Agent", b =>
                {
                    b.HasOne("TravelCompany.DataAccess.Agency", "Agency")
                        .WithMany("Agents")
                        .HasForeignKey("AgencyUUID");

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("TravelCompany.DataAccess.Agency", b =>
                {
                    b.Navigation("Agents");
                });
#pragma warning restore 612, 618
        }
    }
}
